### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by arwhirang** [brmson/blanqa#2]
hello.
When I proceed to installation step 6th(mvn verify), I bumped into connection failed. Error messages are written below.
Connect to mu.lti.cs.cmu.edu:8081 [mu.lti.cs.cmu.edu/128.2.207.11] failed: Connection timed out

Mayhaps the cmu server has stopped working?

**Comment by pasky** [comment]
Hi! Does the issue still persist? The server is replying now.

**Comment by arwhirang** [comment]
Thank you. I found that it was the problem of my country. I'll try using proxy connection.

**Comment by arwhirang** [comment]
Actually, I think there might be some error?? things below are my messages when I applied proxy connection.

[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building BlanQA the Practical QA Pipeline 0.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://mu.lti.cs.cmu.edu:8081/nexus/content/repositories/releases/eij/uima-as-core/2.4/uima-as-core-2.4.pom
Downloading: http://mu.lti.cs.cmu.edu:8081/nexus/content/repositories/thirdparty/eij/uima-as-core/2.4/uima-as-core-2.4.pom
Downloading: http://mu.lti.cs.cmu.edu:8081/nexus/content/repositories/releases/edu/cmu/lti/oaqa/ecd/uima-ecd/2.4.0-SNAPSHOT/maven-metadata.xml
Downloading: http://mu.lti.cs.cmu.edu:8081/nexus/content/repositories/thirdparty/edu/cmu/lti/oaqa/ecd/uima-ecd/2.4.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata edu.cmu.lti.oaqa.ecd:uima-ecd:2.4.0-SNAPSHOT/maven-metadata.xml from/to oaqa (http://mu.lti.cs.cmu.edu:8081/nexus/content/repositories/releases): Connection to http://mu.lti.cs.cmu.edu:8081 refused
[WARNING] Could not transfer metadata edu.cmu.lti.oaqa.ecd:uima-ecd:2.4.0-SNAPSHOT/maven-metadata.xml from/to oaqa-thirdparty (http://mu.lti.cs.cmu.edu:8081/nexus/content/repositories/thirdparty): Connection to http://mu.lti.cs.cmu.edu:8081 refused
...

After I look into it, I found that the first url does not have contents I'm looking for.
There's no "eij"  under "http://mu.lti.cs.cmu.edu:8081/nexus/content/repositories/releases/"

Same thing happened to other urls, too. 

Thanks in advance.

**Comment by pasky** [comment]
I see.  It seems some of the files might have been removed.  I've put raw contents of my copy of ~/.m2/repository/eij maven cache to http://pasky.or.cz/dev/brmson/eij - I'm not sure if that helps?  I can put some of the other files in my maven cache there if we figure out what these are, but otherwise I'm not able to support the blanqa build system too much anymore.

**Comment by arwhirang** [comment]
OK. Thank you for kind reply.

**Comment by k0105** [comment]
Since copying files into the Maven cache is not too robust, I just wrote a small script that cleanly downloads and adds the dependencies:

```
#!/bin/sh

# Install prerequisites
apt-get install default-jdk uima-utils maven git

# Clone main project
git clone https://github.com/brmson/blanqa.git
cd blanqa

# Clone and build UIMA ECD dependency
git clone https://github.com/brmson/uima-ecd
cd uima-ecd
mvn install
cd ..

# Download resources
for i in opennlp netagger wordnet questionanalysis stanfordparser indices; do wget http://pasky.or.cz/dev/brmson/res-$i.zip; unzip res-$i.zip; done

# Add dataset
mkdir data
wget https://github.com/downloads/oaqa/helloqa/guten.tar.gz
tar -C data -xf guten.tar.gz

# Download eij dependencies that are not available through CMU anymore
mkdir lib
cd lib
wget http://pasky.or.cz/dev/brmson/eij/annotation-uima-jms/1.0/annotation-uima-jms-1.0.jar
wget http://pasky.or.cz/dev/brmson/eij/ephyra/1.0/ephyra-1.0.jar
wget http://pasky.or.cz/dev/brmson/eij/json/1.0/json-1.0.jar
wget http://pasky.or.cz/dev/brmson/eij/maxent/1.0/maxent-1.0.jar
wget http://pasky.or.cz/dev/brmson/eij/opennlp-tool/1.0/opennlp-tool-1.0.jar
wget http://pasky.or.cz/dev/brmson/eij/racr-libx/1.0/racr-libx-1.0.jar
wget http://pasky.or.cz/dev/brmson/eij/racr/1.0/racr-1.0.jar
wget http://pasky.or.cz/dev/brmson/eij/simmetric/1.0/simmetric-1.0.jar
wget http://pasky.or.cz/dev/brmson/eij/stanford-ner/1.0/stanford-ner-1.0.jar
wget http://pasky.or.cz/dev/brmson/eij/stanford-parser/1.0/stanford-parser-1.0.jar
wget http://pasky.or.cz/dev/brmson/eij/uima-as-core/2.4/uima-as-core-2.4.jar
wget http://pasky.or.cz/dev/brmson/eij/uimaj-as-activemq/1.0/uimaj-as-activemq-1.0.jar
wget http://pasky.or.cz/dev/brmson/eij/wikixmlj/r43/wikixmlj-r43.jar

# Add eij dependencies to Maven
cd ..
mvn install:install-file -Dfile=./lib/racr-libx-1.0.jar -DgroupId=eij -DartifactId=racr-libx -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=./lib/uimaj-as-activemq-1.0.jar -DgroupId=eij -DartifactId=uimaj-as-activemq -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=./lib/uima-as-core-2.4.jar -DgroupId=eij -DartifactId=uima-as-core -Dversion=2.4 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=./lib/annotation-uima-jms-1.0.jar -DgroupId=eij -DartifactId=annotation-uima-jms -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=./lib/maxent-1.0.jar -DgroupId=eij -DartifactId=maxent -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=./lib/json-1.0.jar -DgroupId=eij -DartifactId=json -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=./lib/stanford-ner-1.0.jar -DgroupId=eij -DartifactId=stanford-ner -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=./lib/racr-1.0.jar -DgroupId=eij -DartifactId=racr -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=./lib/ephyra-1.0.jar -DgroupId=eij -DartifactId=ephyra -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=./lib/stanford-parser-1.0.jar -DgroupId=eij -DartifactId=stanford-parser -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=./lib/opennlp-tool-1.0.jar -DgroupId=eij -DartifactId=opennlp-tool -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=./lib/wikixmlj-r43.jar -DgroupId=eij -DartifactId=wikixmlj -Dversion=r43 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=./lib/simmetric-1.0.jar -DgroupId=eij -DartifactId=simmetric -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true

# Compile main project
mvn verify

# To run
#mvn -q exec:java -Dexec.arguments="phases.blanqa"
```

Maybe it's useful to you.

Best wishes,
Joe

**Comment by k0105** [comment]
Can't this issue be closed? The problem was that CMU discontinued hosting the eij dependencies and was solved by Petr mirroring them on his server and me providing a build script to use them. No more posts for 2 months - I don't think there's anything else to discuss here.

**Comment by pasky** [comment]
I don't think it's harmful leaving it open as that gives people a way to easily see it if they encounter the problem. Of course, the most awesome solution would be if we added your script to the git repo and referenced it in the README - pull requests heartily welcome!!

**Comment by k0105** [comment]
Just for completeness sake: It looks like CMU moved their dependencies and thus files like edu.cmu.minorthird:minorthird:jar:20080611 can no longer be retrieved. While this file could still be obtained from SourceForge, others like org.tartarus.snowball:stemmer:pom:20120530 are not that easily available afaik. Accordingly, BlanQA cannot be built anymore.

**Comment by k0105** [comment]
[I've been able to build BlanQA again by copying over the dependencies from OpenEphyra and adding the corresponding install-file statements.]
